# Generated by Django 4.1 on 2022-08-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_game_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='list_id',
            new_name='imdb_id',
        ),
    ]
