# Generated by Django 4.1 on 2022-08-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_game_api', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='losergif',
            name='gif',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='winnergif',
            name='gif',
            field=models.URLField(),
        ),
    ]
